use super::types::*;

pub fn create_items() -> Vec<Item> {
    vec![
        Item {
            id: "facility_keycard".into(), name: "Facility Keycard".into(),
            description: "A standard keycard with the Prometheus Facility logo.".into(),
            detailed_description: "A laminated keycard with a magnetic stripe and embedded RFID chip. The Prometheus Facility logo is printed in metallic silver. The name 'Dr. Elena Prometheus' is barely visible beneath scratch marks. A level-3 clearance indicator grants access to most areas.".into(),
            category: ItemCategory::Key, usable: true, combinable: false,
            combine_result: None, combine_with: None, use_target: Some("main_hall_north".into()),
            weight: 0.05, icon: "\u{1f511}".into(), takeable: true,
        },
        Item {
            id: "research_journal".into(), name: "Research Journal".into(),
            description: "A leather-bound journal filled with dense scientific notes.".into(),
            detailed_description: "A well-worn leather-bound journal with cramped handwriting, complex equations, and diagrams. Entries document increasingly erratic experiments. The final entry reads: 'The core is unstable. If the energy threshold is exceeded, the results will be catastrophic. I must shut it down before...' The sentence is unfinished.".into(),
            category: ItemCategory::Document, usable: false, combinable: false,
            combine_result: None, combine_with: None, use_target: None,
            weight: 0.3, icon: "\u{1f4d3}".into(), takeable: true,
        },
        Item {
            id: "usb_drive".into(), name: "Encrypted USB Drive".into(),
            description: "A military-grade encrypted USB drive.".into(),
            detailed_description: "A matte-black USB drive with military-grade encryption markings. It's heavier than standard, suggesting additional hardware. A tiny inscription reads: 'P-PROJECT: DELTA LEVEL - EYES ONLY'.".into(),
            category: ItemCategory::Quest, usable: true, combinable: false,
            combine_result: None, combine_with: None, use_target: Some("network_hub".into()),
            weight: 0.05, icon: "\u{1f5f3}".into(), takeable: true,
        },
        Item {
            id: "network_cable".into(), name: "High-Speed Network Cable".into(),
            description: "A thick fiber-optic cable with custom connectors.".into(),
            detailed_description: "A thick, braided fiber-optic cable with custom-machined connectors. The connectors don't match any standard equipment. A label reads 'Custom Build - Prometheus Engineering Dept.'".into(),
            category: ItemCategory::Tool, usable: true, combinable: true,
            combine_result: Some("patched_connection".into()), combine_with: Some("server_room".into()),
            use_target: Some("server_room".into()), weight: 0.8, icon: "\u{1f50c}".into(), takeable: true,
        },
        Item {
            id: "hazard_suit".into(), name: "Hazmat Protection Suit".into(),
            description: "A full-body hazardous materials protection suit.".into(),
            detailed_description: "A full-body hazmat suit in pristine condition with integrated breathing apparatus, HUD display, and reinforced gloves. The exterior is white with orange accents and the Prometheus Facility logo.".into(),
            category: ItemCategory::Tool, usable: true, combinable: false,
            combine_result: None, combine_with: None, use_target: Some("research_lab".into()),
            weight: 3.5, icon: "\u{2620}".into(), takeable: true,
        },
        Item {
            id: "lab_notes".into(), name: "Scattered Lab Notes".into(),
            description: "Handwritten notes detailing the Prometheus Core experiment.".into(),
            detailed_description: "Several pages of notes with chemical formulas and reactor diagrams describing 'the Prometheus Core'. A note in the margin reads: 'Office code: 7-3-1-9 - H.P.'".into(),
            category: ItemCategory::Document, usable: false, combinable: false,
            combine_result: None, combine_with: None, use_target: None,
            weight: 0.1, icon: "\u{1f4dd}".into(), takeable: true,
        },
        Item {
            id: "chemical_formula".into(), name: "Chemical Formula Sheet".into(),
            description: "A formula for creating a stabilization compound.".into(),
            detailed_description: "A precise formula for 'Prometheus Stabilizer' - one part 'Strange Compound' to three parts 'Antidote Base'. A note reads: 'Mix ONLY in the chemical storage fume hood.'".into(),
            category: ItemCategory::Document, usable: true, combinable: true,
            combine_result: Some("prometheus_stabilizer".into()), combine_with: Some("chemical_storage".into()),
            use_target: Some("chemical_storage".into()), weight: 0.02, icon: "\u{1f9ea}".into(), takeable: true,
        },
        Item {
            id: "circuit_breaker".into(), name: "Circuit Breaker Module".into(),
            description: "A replacement circuit breaker for the generator room.".into(),
            detailed_description: "A heavy industrial circuit breaker 'Model QB-7' rated for extreme loads, manufactured specifically for the Prometheus Facility.".into(),
            category: ItemCategory::Tool, usable: true, combinable: false,
            combine_result: None, combine_with: None, use_target: Some("generator_room".into()),
            weight: 2.0, icon: "\u{26a1}".into(), takeable: true,
        },
        Item {
            id: "old_radio".into(), name: "Vintage Shortwave Radio".into(),
            description: "An old but functional shortwave radio.".into(),
            detailed_description: "A military-surplus shortwave radio with hand-crank generator. A frequency is scribbled on the back: '147.3 MHz - Emergency Channel'.".into(),
            category: ItemCategory::Tool, usable: true, combinable: false,
            combine_result: None, combine_with: None, use_target: None,
            weight: 1.5, icon: "\u{1f4fb}".into(), takeable: true,
        },
        Item {
            id: "toolbox".into(), name: "Mechanic's Toolbox".into(),
            description: "A well-stocked toolbox with various instruments.".into(),
            detailed_description: "A red metal toolbox with screwdrivers, wrenches, multimeter, wire strippers, soldering iron, and various connectors.".into(),
            category: ItemCategory::Tool, usable: false, combinable: true,
            combine_result: Some("repair_kit".into()), combine_with: Some("circuit_breaker".into()),
            use_target: None, weight: 4.0, icon: "\u{1f527}".into(), takeable: true,
        },
        Item {
            id: "signal_flare".into(), name: "Signal Flare".into(),
            description: "A military-grade signal flare for emergency use.".into(),
            detailed_description: "A standard military signal flare visible for over 15 kilometers. Instructions: remove cap, point skyward, pull the ring.".into(),
            category: ItemCategory::Tool, usable: true, combinable: false,
            combine_result: None, combine_with: None, use_target: Some("exit_chamber".into()),
            weight: 0.3, icon: "\u{1f525}".into(), takeable: true,
        },
        Item {
            id: "binoculars".into(), name: "High-Powered Binoculars".into(),
            description: "Military-grade binoculars with night vision.".into(),
            detailed_description: "High-powered military binoculars with built-in night vision and range-finding reticle. Can see incredible detail from the observation deck.".into(),
            category: ItemCategory::Tool, usable: true, combinable: false,
            combine_result: None, combine_with: None, use_target: Some("observation_deck".into()),
            weight: 0.8, icon: "\u{1f441}".into(), takeable: true,
        },
        Item {
            id: "director_key".into(), name: "Director's Master Key".into(),
            description: "An ornate golden key with the director's initials.".into(),
            detailed_description: "An ornate golden key decorated with circuit traces and initials 'H.P.'. An engraving reads: 'For the one who follows the light.'".into(),
            category: ItemCategory::Key, usable: true, combinable: false,
            combine_result: None, combine_with: None, use_target: Some("directors_office".into()),
            weight: 0.2, icon: "\u{1f6e1}".into(), takeable: true,
        },
        Item {
            id: "photograph".into(), name: "Old Photograph".into(),
            description: "A photograph of the facility's construction.".into(),
            detailed_description: "A black-and-white photo of the facility under construction. Dr. Helena Prometheus stands at the entrance. On the back: 'Day 1 of our greatest endeavor.' A small map shows a hidden passage behind the main server rack.".into(),
            category: ItemCategory::Document, usable: false, combinable: false,
            combine_result: None, combine_with: None, use_target: None,
            weight: 0.01, icon: "\u{1f4f7}".into(), takeable: true,
        },
        Item {
            id: "antidote".into(), name: "Antidote Compound".into(),
            description: "A vial of clear liquid labeled 'Universal Antidote Base'.".into(),
            detailed_description: "A small vial containing a clear, odorless liquid labeled 'Universal Antidote Base - Compound Alpha'. One of the base compounds needed for the Prometheus Stabilizer formula.".into(),
            category: ItemCategory::PuzzlePiece, usable: true, combinable: true,
            combine_result: Some("prometheus_stabilizer".into()), combine_with: Some("strange_compound".into()),
            use_target: Some("chemical_storage".into()), weight: 0.1, icon: "\u{1f9ec}".into(), takeable: true,
        },
        Item {
            id: "strange_compound".into(), name: "Strange Luminous Compound".into(),
            description: "A vial of glowing green liquid with unusual properties.".into(),
            detailed_description: "A small vial containing viscous green liquid that glows with an inner light, pulsing rhythmically. The label reads 'Sample Omega-7 - DO NOT DISTRIBUTE'.".into(),
            category: ItemCategory::PuzzlePiece, usable: true, combinable: true,
            combine_result: Some("prometheus_stabilizer".into()), combine_with: Some("antidote".into()),
            use_target: Some("chemical_storage".into()), weight: 0.1, icon: "\u{1f7e2}".into(), takeable: true,
        },
        Item {
            id: "energy_cell".into(), name: "Charged Energy Cell".into(),
            description: "A powerful energy cell harvested from the experiment.".into(),
            detailed_description: "A crystalline energy cell that pulses with captured power. Its energy signature matches the Prometheus Core's frequency, suggesting it could stabilize the core device.".into(),
            category: ItemCategory::PuzzlePiece, usable: true, combinable: false,
            combine_result: None, combine_with: None, use_target: Some("experiment_chamber".into()),
            weight: 0.5, icon: "\u{1f50b}".into(), takeable: true,
        },
        Item {
            id: "power_cell".into(), name: "Charged Power Cell".into(),
            description: "A high-capacity power cell from the generator.".into(),
            detailed_description: "A large power cell rated 'QC-7 Series - 50,000 mAh'. Could be essential for restoring full power to the facility's systems.".into(),
            category: ItemCategory::Tool, usable: true, combinable: false,
            combine_result: None, combine_with: None, use_target: Some("generator_room".into()),
            weight: 1.5, icon: "\u{1f50b}".into(), takeable: true,
        },
        Item {
            id: "decrypted_files".into(), name: "Decrypted Project Files".into(),
            description: "Classified documents revealing the facility's true purpose.".into(),
            detailed_description: "Decrypted files revealing Project Prometheus - an attempt to create sustainable energy from quantum vacuum. The project was successful but dangerously unstable.".into(),
            category: ItemCategory::Document, usable: false, combinable: false,
            combine_result: None, combine_with: None, use_target: None,
            weight: 0.05, icon: "\u{1f4c4}".into(), takeable: true,
        },
        Item {
            id: "biometric_key".into(), name: "Biometric Access Key".into(),
            description: "A device that mimics biometric authentication signals.".into(),
            detailed_description: "A handheld device showing 'AUTH EMULATOR v3.1'. When activated near a biometric lock, it generates valid authentication credentials.".into(),
            category: ItemCategory::Key, usable: true, combinable: false,
            combine_result: None, combine_with: None, use_target: Some("server_room".into()),
            weight: 0.15, icon: "\u{1f4f1}".into(), takeable: true,
        },
        Item {
            id: "maintenance_manual".into(), name: "Generator Maintenance Manual".into(),
            description: "Technical manual for the facility's fusion generator.".into(),
            detailed_description: "A thick manual with schematics and maintenance procedures. Hand-written annotations include 'the trick with the quantum breaker - always ground yourself first'.".into(),
            category: ItemCategory::Document, usable: false, combinable: false,
            combine_result: None, combine_with: None, use_target: None,
            weight: 0.5, icon: "\u{1f4d6}".into(), takeable: true,
        },
        Item {
            id: "final_note".into(), name: "Helena's Final Note".into(),
            description: "A personal letter from Dr. Helena Prometheus.".into(),
            detailed_description: "A handwritten letter: 'To whoever finds this - I am Helena Prometheus. I built this facility to save the world. The Core was meant for limitless clean energy. But they wanted to weaponize it. I shut down the main systems. Use the Stabilizer on the Core, then escape through the tunnel. - H.P.'".into(),
            category: ItemCategory::Quest, usable: false, combinable: false,
            combine_result: None, combine_with: None, use_target: None,
            weight: 0.01, icon: "\u{1f4dc}".into(), takeable: true,
        },
        Item {
            id: "prometheus_stabilizer".into(), name: "Prometheus Stabilizer".into(),
            description: "A shimmering compound that can stabilize the Core.".into(),
            detailed_description: "A vial of shimmering, iridescent liquid that shifts between colors. When applied to the Prometheus Core, it should regulate energy output and prevent catastrophic meltdown.".into(),
            category: ItemCategory::Treasure, usable: true, combinable: false,
            combine_result: None, combine_with: None, use_target: Some("experiment_chamber".into()),
            weight: 0.15, icon: "\u{2728}".into(), takeable: true,
        },
        Item {
            id: "prometheus_core".into(), name: "Prometheus Core Fragment".into(),
            description: "A fragment of the legendary Prometheus Core.".into(),
            detailed_description: "A crystalline fragment that radiates controlled energy and serves as the key to the escape tunnel's concealed door.".into(),
            category: ItemCategory::Treasure, usable: true, combinable: false,
            combine_result: None, combine_with: None, use_target: Some("escape_tunnel".into()),
            weight: 0.3, icon: "\u{1f48e}".into(), takeable: true,
        },
    ]
}
