use super::types::*;

// ============================================================
// Puzzle Definitions
// ============================================================

pub fn create_puzzles() -> Vec<Puzzle> {
    vec![
        Puzzle {
            id: "office_code".into(),
            name: "Director's Office Keypad".into(),
            description: "A keypad lock requires a 4-digit code to enter the Director's Office.".into(),
            room_id: "library".into(),
            puzzle_type: PuzzleType::CodeEntry,
            required_items: vec![],
            solution: "7319".into(),
            solved: false,
            reward_item: None,
            reward_flag: Some("office_code_known".into()),
            hint: "The lab notes mentioned a code: 7-3-1-9 - H.P.".into(),
            failure_message: "Incorrect code. The keypad beeps and resets.".into(),
            success_message: "The keypad beeps three times and the lock clicks open! The Director's Office door slides aside.".into(),
        },
        Puzzle {
            id: "create_stabilizer".into(),
            name: "Create the Prometheus Stabilizer".into(),
            description: "Mix the Strange Compound and Antidote in the fume hood to create the Stabilizer.".into(),
            room_id: "chemical_storage".into(),
            puzzle_type: PuzzleType::ItemCombination,
            required_items: vec!["strange_compound".into(), "antidote".into(), "chemical_formula".into()],
            solution: "mix".into(),
            solved: false,
            reward_item: Some("prometheus_stabilizer".into()),
            reward_flag: Some("stabilizer_created".into()),
            hint: "You need both the Strange Compound and the Antidote, plus the formula sheet. Mix them in the fume hood.".into(),
            failure_message: "The fume hood requires the correct ingredients and proportions.".into(),
            success_message: "The compounds react brilliantly! A shimmering iridescent liquid forms in the beaker - the Prometheus Stabilizer! You carefully transfer it to a vial.".into(),
        },
        Puzzle {
            id: "repair_generator".into(),
            name: "Repair the Generator".into(),
            description: "Install the circuit breaker to restore full power to the facility.".into(),
            room_id: "generator_room".into(),
            puzzle_type: PuzzleType::PhysicalInteraction,
            required_items: vec!["circuit_breaker".into(), "toolbox".into()],
            solution: "install".into(),
            solved: false,
            reward_item: None,
            reward_flag: Some("generator_fixed".into()),
            hint: "You need the circuit breaker and the toolbox to make the repair.".into(),
            failure_message: "The generator panel sparks angrily. You need the right tools and parts.".into(),
            success_message: "With practiced precision, you install the quantum breaker. The generator roars to full power! Lights throughout the facility brighten noticeably.".into(),
        },
        Puzzle {
            id: "decrypt_usb".into(),
            name: "Decrypt the USB Drive".into(),
            description: "Use the network hub's decryption workstation to access the USB's data.".into(),
            room_id: "network_hub".into(),
            puzzle_type: PuzzleType::ItemCombination,
            required_items: vec!["usb_drive".into()],
            solution: "decrypt".into(),
            solved: false,
            reward_item: None,
            reward_flag: Some("files_decrypted".into()),
            hint: "The decryption workstation here might be able to crack the USB's encryption.".into(),
            failure_message: "The decryption algorithm needs more processing power or the correct key.".into(),
            success_message: "After minutes of processing, the decryption completes! The files reveal the truth about Project Prometheus.".into(),
        },
        Puzzle {
            id: "stabilize_core".into(),
            name: "Stabilize the Prometheus Core".into(),
            description: "Use the Stabilizer on the Prometheus Core to prevent a catastrophic meltdown.".into(),
            room_id: "experiment_chamber".into(),
            puzzle_type: PuzzleType::ItemCombination,
            required_items: vec!["prometheus_stabilizer".into()],
            solution: "stabilize".into(),
            solved: false,
            reward_item: Some("prometheus_core".into()),
            reward_flag: Some("core_stabilized".into()),
            hint: "The Core is dangerously unstable. You need the Prometheus Stabilizer to calm it.".into(),
            failure_message: "The Core pulses dangerously! You back away as energy discharges crackle through the air.".into(),
            success_message: "You carefully apply the Stabilizer to the Core. The wild energy patterns calm, the blue-white light stabilizes to a steady glow, and a crystalline fragment breaks free. The Core is safe! A concealed door hums open to the north...".into(),
        },
        Puzzle {
            id: "signal_for_help".into(),
            name: "Signal for Rescue".into(),
            description: "Use the signal flare at the surface exit to call for rescue.".into(),
            room_id: "exit_chamber".into(),
            puzzle_type: PuzzleType::PhysicalInteraction,
            required_items: vec!["signal_flare".into()],
            solution: "fire".into(),
            solved: false,
            reward_item: None,
            reward_flag: Some("rescue_called".into()),
            hint: "The signal flare could be seen from miles away. Try using it here.".into(),
            failure_message: "The flare needs to be pointed skyward and fired in an open area.".into(),
            success_message: "You fire the signal flare! It rockets into the night sky, exploding in a brilliant red star visible for kilometers. In the distance, you see headlights responding to your signal. You're going home!".into(),
        },
    ]
}
